# Change these first
owner: hectorsaravia # Your GitHub organization or username, where this repository lives
repo: hectorsaravia.works-status # The name of this repository

sites:
  - name: hectorsaravia.works
    url: https://hectorsaravia.works

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hectorsaravia.works
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.hectorsaravia.works
  introTitle: "Status pago for **hectorsaravia.works**"
  introMessage: This website is served with GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
